using System.Text;

namespace Zenvin.ScriptGeneration {
	public static class ScriptFactoryUtility {

		public static void AppendAutoGeneratedWarning (StringBuilder sb) {
			if (sb == null) {
				return;
			}
			sb.AppendLine ("// ----------------------------------------------------");
			sb.AppendLine ("//                       WARNING");
			sb.AppendLine ("// This file was generated automatically.");
			sb.AppendLine ("// Manual changes to it may lead to unwanted behaviour.");
			sb.AppendLine ("// ----------------------------------------------------");
		}

	}
}